In [12]:
import torch
# print(torch.cuda.is_available())
# print(torch.cuda.get_device_name(0))

In [13]:
from utils.data_generator_discrete import *
dir_path = "/Users/yamashitanatsuki/Documents/Python/CTMCxDeepSets"
name = "test_base"
sumples = 10000
TRMG = DiagonalTransitionRateMatrixGenerator(4)
trm = TRMG.generateMatrix(TRMG.setDiagonalElement_byLifespan,100)
dg = DataGenerator(trm, sumples,)

d = DirichletDeltaT(min_intervals=2, max_intervals=10)
M = dg.generate_matrix(d.sample)
dg.generate_dataFile(M,name,dir_path)

ModuleNotFoundError: No module named 'likelihood'

In [ ]:
import pandas as pd
df = pd.read_csv("notebooks/deck.csv",header=None)
display(df.head())

          0         1          2
0  0.021916  0.136360   0.101534
1  0.022061  0.140803   0.101830
2  1.000000  1.000000  22.000000
3  1.000000  1.000000   2.000000
4  1.000000  1.000000   1.000000

In [ ]:
df = df[df[0]==4]
display(df.head())

Empty DataFrame
Columns: [0, 1, 2]
Index: []

In [ ]:
import pandas as pd
df = pd.read_csv("/mnt/ssd/datas/real_data/pavement/samples_1716/10_1716_4.csv", header=None)
display(df.head())

          0         1          2         3
0 -0.036205  0.036205   0.000000  0.000000
1  0.000000 -0.055506   0.055506  0.000000
2  0.000000  0.000000  -0.123427  0.123427
3  0.000000  0.000000   0.000000  0.000000
4  1.000000  1.000000  14.000000  0.000000

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

def df_to_image(df, path="df_table.png", dpi=800, font_size=10):
    fig, ax = plt.subplots()
    ax.axis("off")

    tbl = ax.table(
        cellText=df.values,
        colLabels=df.columns,
        cellLoc="center",
        loc="center",
    )
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(font_size)
    tbl.scale(1, 2)  # 行の高さを少し広げる

    plt.tight_layout()
    fig.savefig(path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


df = pd.read_csv("notebooks/eval_error.csv",)
df.loc[df["name"]=="shoban","name"]="deck"
wide = (
    df.pivot_table(
        index=["name","%","condition_state"],          # 行：同じnameを集約
        columns="metric",  # 列：percentileごとに列化
        values="value",        # 中身：value
        aggfunc="first"        # 重複がある場合の扱い（状況に応じて変更）
    )
    
)

wide.to_csv("error_table.csv",index=True)
import dataframe_image as dfi


# まずこれを試す（環境によって動く/動かないが、playwright回避になることがある）
# dfi.export(wide, "table.png", table_conversion="matplotlib")

# 多少VSCodeっぽく寄せるなら（例）
styled = wide.style.set_table_styles(
    [{"selector":"th, td", "props":[("border","1.2px solid #ddd"), ("padding","7px")]}]
).set_properties(**{"text-align": "center"})

# まずこれを試す（環境によって動く/動かないが、playwright回避になることがある）
dfi.export(wide, "table.png", fontsize=10,table_conversion="matplotlib",dpi=800)

In [2]:
import pandas as pd

df = pd.read_csv("/mnt/ssd/datas/discrete_test_N5000_ll/0_5000_4.csv",header=None)
display(df.head(10))

          0         1          2         3
0 -0.010755  0.010755   0.000000  0.000000
1  0.000000 -0.010595   0.010595  0.000000
2  0.000000  0.000000  -0.027714  0.027714
3  0.000000  0.000000   0.000000  0.000000
4 -0.012148  0.012148   0.000000  0.000000
5  0.000000 -0.010214   0.010214  0.000000
6  0.000000  0.000000  -0.027083  0.027083
7  0.000000  0.000000   0.000000  0.000000
8  1.000000  2.000000  57.400000  0.000000
9  3.000000  4.000000  57.400000  0.000000

In [ ]:
import pandas as pd 
data_dir = "/mnt/ssd/datas/"